#!/bin/bash
rm .gitignore
rm .gitnore
touch .gitignore
echo -e "/run_scipt\n*~" > .gitignore
git add .
git commit -m"update git ignore"
echo -e "#!/bin/bash\nchmod --reference=olleh hello" > 10-mirror_permissions
git add .
git commit -m"mirror permissions"
touch 11-directories_permissions
chmod +x 11-directories_permissions
echo -e "#!/bin/bash\nchmod +X ../" > 11-directories_permissions
git add .
git commit -m"directories permission"
git touch 13-change_group
chmod +x 13-change_group
echo -e "#!/bin/bash\nchgrp school hello" > 13-change_group
git add .
git commit -m"change group script"
git push
